apiVersion: v1
kind: Secret
metadata:
  name: fileconversion-secrets
  namespace: fileconversion
type: Opaque
stringData:
  rabbitmq-user: your-rabbitmq-user
  rabbitmq-pass: your-rabbitmq-pass
  rabbitmq-keda-host: your-rabbitmq-keda-host
  db-user: your-db-user
  db-password: your-db-password
  db-name: your-db-name
  connection-string: Host=postgres;Port=5432;Database=your-db-name;Username=your-db-user;Password=your-db-password