apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-pvc
  namespace: fileconversion
spec:
  accessModes:
    - ReadWriteOnce # For Kind (instead of ReadWriteMany)
  resources:
    requests:
      storage: 5Gi